# Generated by Django 5.1.7 on 2025-03-10 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('letra', models.CharField(max_length=1, unique=True, verbose_name='Letra')),
            ],
            options={
                'ordering': ['letra'],
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Registrado')),
                ('estado', models.CharField(blank=True, choices=[('r', 'Revisión'), ('a', 'Aprobado')], default='r', max_length=1, verbose_name='Estado')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
